/*
결과 컬럼 : ITEM_ID, ITEM_NAME, RARITY
조건: 더이상 업그레이드 할 수 없는 아이템 대상. 아이템ID 기준 내림차순
PARENT_ITEM_ID에 ITEM_ID가 잇으면 안됨
*/

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
LEFT JOIN ITEM_TREE AS T
ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC
