/*
결과 컬럼 : WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, FREEZER_YN
조회 : 냉동시설 여부 NULL이면 'N'으로 출력, 결과는 창고 ID로 오름차순
*/

SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IF(FREEZER_YN IS NULL, 'N', FREEZER_YN) AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME LIKE "%_경기%"
ORDER BY WAREHOUSE_ID
