/*
결과 컬럼 : USER_ID, PRODUCT_ID
조건 : 회원 ID 기준 오름차순, 회원 ID 같으면 상품 ID 기준으로 내림차순 
*/

SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(PRODUCT_ID) >= 2
ORDER BY USER_ID, PRODUCT_ID DESC
