/*
결과 칼럼 : MEMBER_ID, MEMBER_NAME, GENDER, DATE_OF_BIRTH
조건 : 생일이 3월인 여성 회원의 ID, 이름, 성별, 생년월일 조회 & 전화번호 NULL이면 출력대상 제외 & 회원 ID 오름차순 정렬
*/

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL AND MONTH(DATE_OF_BIRTH) = 3 AND GENDER = 'W'
ORDER BY MEMBER_ID
