/*
결과 컬럼 : ITEM_ID, ITEM_NAME
조건 : ROOT아이템의 ITEM_ID, ITEM_NAME 출력. ITEM_ID 오름차순 정렬
*/

SELECT I.ITEM_ID, I.ITEM_NAME
FROM ITEM_TREE AS T
JOIN ITEM_INFO AS I
ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID
