/*
결과 컬럼 : AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
조건 : 2022년 1월 도서 데이터 기준, 카테고리별 매출액 구하기, 저자ID 오름차순, 카테고리 내림차순
*/

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES AS BS
JOIN BOOK AS B
ON B.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR AS A
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE MONTH(BS.SALES_DATE) < 2  
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
